service: random-image
provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  environment:
    STAGE: '${opt:stage}'
functions:
  handler:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
custom:
  serverless-offline:
    port: 3002
  webpack:
    webpackConfig: ../../../cantara/static/.temp/sls-api_serverlessWebpackConfig.js
    includeModules:
      packagePath: ./package.json
    packager: npm
plugins:
  - 'C:/Users/maxim/DEV/cantara/node_modules/serverless-offline'
  - 'C:/Users/maxim/DEV/cantara/node_modules/serverless-webpack'
