
name: "Cantara-Deployment"
on: # Deploy Client App to Surge and
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://lambci/lambda:build-nodejs12.x
    - run: |
        npm install
        npm i -g cantara
        cantara build random-image-app
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker://lambci/lambda:build-nodejs12.x
    - run: cantara test 
